name: triggered
on:
  workflow_run:
    workflows: [Parent]
    types:
      - completed

jobs:
  cleanup:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }} # so we can still re-run single jobs in case of failure
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cleanup workflow build artifacts
        run: |
          REPO=${{ github.repository }}
          PARENT_EVENT_PATH=$(jq -r .workflow.path $GITHUB_EVENT_PATH)
          TEST_RUN_ID=${{ github.event.workflow_run.payload.workflow_run.id }}
          PARENT_RUN_ID=$(jq -r .head_run_id $PARENT_EVENT_PATH)
          echo "parent run id is $PARENT_RUN_ID with default $TEST_RUN_ID"

          echo "Fetching list of artifacts id (up to 100) for run id ${PARENT_RUN_ID:=TEST_RUN_ID}..."
          ARTIFACT_IDS=$(gh api -XGET /repos/$REPO/actions/runs/${PARENT_RUN_ID:=TEST_RUN_ID}/artifacts -F per_page=100  --jq '.artifacts[] | select( .name ==  "build") | .id')

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting build artifacts..."
          for ARTIFACT_ID_TO_DELETE in ${ARTIFACT_IDS}; 
          do
            gh api -X DELETE /repos/$REPO/actions/artifacts/$ARTIFACT_ID_TO_DELETE
          done
          echo "Done"

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
