name: triggered
on:
  workflow_run:
    workflows: [Parent]
    types:
      - completed

jobs:
  cleanup:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }} # so we can still re-run single jobs in case of failure
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cleanup workflow build artifacts
        run: |
          REPO=${{ github.repository }}
          PARENT_ARTIFACTS_URL=$(jq -r .workflow_run.artifacts_url $GITHUB_EVENT_PATH)

          echo "Fetching list of artifacts id (up to 100)..."
          ARTIFACT_IDS=$(gh api -XGET $PARENT_ARTIFACTS_URL -F per_page=100  --jq '.artifacts[] | select( .name ==  "build") | .id')

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting build artifacts..."
          for ARTIFACT_ID_TO_DELETE in ${ARTIFACT_IDS}; 
          do
            gh api -X DELETE /repos/$REPO/actions/artifacts/$ARTIFACT_ID_TO_DELETE
          done
          echo "Done"

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
