name: Parent 

on:
  pull_request: ~
  push:
    branches:
      - master
      - main
      - develop
      - demo

jobs:
  cleanup:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }} # so we can still re-run single jobs in case of failure
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
